name: Manual Dispatch Workflow

on:
  workflow_dispatch:

env:
  WORKFLOW_FILE_NAME: uptime.yml
  PAT: ${{ secrets.GH_PAT || github.token }}

jobs:
  dispatch-and-curl:
    runs-on: ubuntu-latest
    steps:
      - name: Generate random sleep duration
        id: random-sleep
        run: |
          # Generate random number between 300 and 600 seconds (5-10 minutes)
          SLEEP_DURATION=$((RANDOM % 301 + 300))
          echo "Sleeping for $SLEEP_DURATION seconds"
          echo "sleep_duration=$SLEEP_DURATION" >> $GITHUB_OUTPUT

      - name: Sleep for random duration
        run: sleep ${{ steps.random-sleep.outputs.sleep_duration }}

      - name: Execute cURL command
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $PAT" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ env.WORKFLOW_FILE_NAME }}/dispatches \
            -d '{"ref":"main"}'

      - name: Sleep for 1 min
        run: sleep 60

      - name: Execute cURL command
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $PAT" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/manually.yml/dispatches \
            -d '{"ref":"main"}'

